### ISSUE TITLE
Rendering bug on Firefox Android

### ISSUE THREAD

**Issue by chr15m** [elishaterada/feathercss#2]
I noticed a small bug on Firefox Android (see the 2 next to "bathrooms"):

![image](https://user-images.githubusercontent.com/67130/107175304-737fc200-6a07-11eb-8201-01f8f3de6648.png)

**Comment by elishaterada** [comment]
Thanks for reporting, I just fixed it on v1.1.5

**Comment by chr15m** [comment]
Works on my device. Thanks!
